name: 'PR Todo Checker'

description: 'Find and comment on TODOs in pull requests'

branding:
  icon: 'check-square'
  color: 'green'

inputs:
  token:
    description: 'GitHub token'
    required: true
  exclude:
    description:
      'Exclude file patterns. User list of globs separated by new line.'
    required: false
  comment_on_todo:
    description: 'Comment on the TODO in the PR'
    required: false
    default: 'true'
  comment_body:
    description:
      'Comment body to use when a TODO is found. Use {todo} to insert the TODO
      message.'
    required: false
    default: "A new Todo was discovered. If it is not a priority right now,\
      consider marking it for later attention.\n{todo}\n"
  comment_checkbox:
    description:
      'Checkbox message to ignore the TODO. Use {todo} to insert the TODO
      message.'
    required: false
    default: 'Ignore'
  enable_ignore_checkbox:
    description:
      'Enable the ignore checkbox in TODO comments. When disabled, users should
      use GitHub''s native "Resolve conversation" feature instead.'
    required: false
    default: 'false'
  custom_todo_matcher:
    description: "Add custom comment indicators for specific file types. Use
      JSON format.\
      Example: {'js': ['//', '/*'], 'py': ['#']}"
    required: false
    default: '{}'
  custom_ignore_matcher:
    description: "Add custom regex to ignore TODOs that match in the same line.\
      Example: my-issue-website.com"
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
